build:
  image: quay.io/reddit/go-debpkger:ubuntu-14.04_go-1.6.3
  commands:
    - ./build
    - ./debian/rules binary

publish:
  s3:
    region: "us-east-1"
    bucket: "reddit-packages"
    source: etcd_*_*.deb
    target: /any/amd64/
